# Generated by Django 6.0.6 on 2026-06-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0007_signet'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
